services:
  postgres:
    image: postgres:16
    container_name: hr_analytics_postgres
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
      POSTGRES_DB: hr_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

